### ISSUE TITLE
Add more build instructions for non-Java folks

### ISSUE THREAD

**Issue by TheWaveWarden** [Berikai/bitwig-theme-editor#1]
Hi, very excited about this project.

I tried to run it, but the README just says to run a `bitwig-theme-editor.jar`, which to start with doesn't exist in the repo. So presumably something has to be built first? Tried to run the `gradlew.bat` on Windows, but didn't get any further.

It would be nice if you could add some basic instructions on how to get this running for us not aquainted with Java/Gradle :)

**Comment by Berikai** [comment]
Hi, thank you for your interest on the project!

README refers to the prebuilt binary which you can find in the [releases](https://github.com/Berikai/bitwig-theme-editor/releases) section of this repository. If you want to build it yourself, I strongly recommend you to use a Java IDE, since these environments comes with all the necessary tools to build the project and make the process a lot easier.

I'll update the README with more clear instructions.

**Comment by TheWaveWarden** [comment]
Ah of course! I missed the releases page. Thanks for getting back!
