### ISSUE TITLE
No Horizontal Grid Lines / No Loop Region Highlight 

### ISSUE THREAD

**Issue by Zacchino** [Berikai/bitwig-theme-editor#13]
Hello Berikai!

I keep seeing 2 small issues that are a little puzzling, since it affect the main arranger view:

1. There's no Horizontal Grid Lines (separating the tracks in the Arranger), only vertical ones. Is that something that can be fixed?

2. Same thing with the Loop Region, when turned on, there's no way to see within the Arranger where the Loop Region extends. Only the top scroll bar indicates where the region starts and stops.

Maybe these are limitation from the Theme Editor itself? Or some lack of control given by the Bitwig.jar file who knows?

_PS: So grateful to finally see a Theme Editor for Bitwig! Thanks so much for all you guys hard work! We already got themes that are super elegant and thoroughly thought out... Makes Bitwig even more enjoyable than it ever was!_

**Comment by Berikai** [comment]
Hello, Zacchino!

To be honest, I'm not really familiar with the Bitwig UI itself. I'm not even a daily Bitwig user.

I've made the switch from Ableton a few months ago and saw that there was no theming feature for Bitwig. When I check Bitwig's code with a decompiler, just out of curiosity, I've seen that most of the color values are stored altogether with their name and color value in 2 main places. 

So, I made this theme editor (patcher) that does two things: extracting the color values with their name and overwriting new values due to the changes on the extracted info... and I released it to the community, along with some really basic proof of concept themes.

With the amazing effort the community put into finding what each value actually does in [this spreadsheet](https://docs.google.com/spreadsheets/d/1iDRYxo2RMPbe8ldjIJqW2GKF_mb1Ldy4Fg6RKudc5jI/edit?gid=802713321#gid=802713321), I've made the [Theme Editor WebUI](https://bitwig.berikai.dev), which I couldn't continue developing for now because of some other personal life priorities of mine, but gonna get back into it in the future I suppose.

Anyways, here is my try at answering:
**It's probably limited because of the way this theme editor works and the values you are talking about are probably hardcoded somewhere else in the code, though I haven't checked specifically.**

Sorry for the long story and bunch of excuses. In the end, I'm just the guy who coded the bytecode patcher for Bitwig's jar file to make theming (somewhat) possible

Thanks for the kind words, appreciate it <3

**Comment by Zacchino** [comment]
Wow I don’t know how to thank you enough for your very clear explanation…

Turns out, after talking to one of the Theme Designer (Lenninst who did the amazing Nord theme), these two issues are totally fixable and he did fix it on his theme yesterday.

So it’s a false alert so to speak… My bad :).
