### ISSUE TITLE
Editor will not run in my current version of Java

### ISSUE THREAD

**Issue by AllGoodMojo** [Berikai/bitwig-theme-editor#15]
UPDATE: Not an issue. Ineptitude on my part. All working. all good

**Comment by Berikai** [comment]
I haven't thought about Java 8 compatibility as a priority for this project. I wrote the code base to be compatible with Java 17, so there are some method calls that are probably not supported in older versions. That means it's not as straightforward as just changing the SDK version and hitting the compile button but if it seems practically beneficial, I'll try to lower the Java SDK version to expand compatibility as lower as possible.

Actually, if you have the latest version of Bitwig Studio installed, you already have a modified JRE 21 installed in the Bitwig's installation folder (`.../bitwig-studio/lib/jre/bin/java` in Linux) to run the Bitwig Studio since Bitwig Studio itself is a Java 21 app, not even Java 17.

**As a solution to your problem, you can run Bitwig's Java to run the theme editor as a perfect option if you don't want to install Java 17 in your system additionally, which works flawlessly.**

**Comment by Berikai** [comment]
It seems like you already fixed your issue while I was writing my comment. It would be great if you kept the original comment along with the update, but it's not necessarily important since the history of comment edits can be viewed later. 

Asking about compatibility with an older version was actually a very reasonable request, and I believe the existence of this issue will be beneficial for others who might encounter similar experiences and seek solutions in the future.

Closing the issue now, happy theming!

**Comment by AllGoodMojo** [comment]
Yo thanks for getting back to me on this one. As you can tell I;m new to
Java stuff. I figured it out and have things working fine it seems. I;ve
altered my report of an issue because this isnt an issue. I installed jdk17
from the oracle archives and your Editor installed just fine it seems and I
dont have to look at the colour orange anymore...Oddly, that was keeping me
from making more music because i couldnt stand looking at the GUI...I also
have studio one and see they are launching vs 7 in october and that has a
clip launcher too...i was dreading the thought of having to relearn Studio
One...Thanks so much!  This is just what I needed. Ed

**Comment by AllGoodMojo** [comment]
we're def crossing paths here....is there something you want me to add/do?
I think there must be others who dont know tech stuff real well who might
be struggling w. this? have a good one

**Comment by Berikai** [comment]
You don't have to do anything. You have a good one too!
