### ISSUE TITLE
Unable to apply theme

### ISSUE THREAD

**Issue by Vocllum** [Berikai/bitwig-theme-editor#16]
Win 11 23H2
Bitwig5.2.5
editor1.4.2
Newer version of Java
After selecting bitwig. jar and replacing the theme file, I opened bw and it still had the default theme. If I export the current theme, the file will be the same as the replaced theme, which means it has been updated, but the bitwig display interface will not have any effect.
I tried to apply the theme six months ago but failed, and I have been trying again recently but still cannot.
During this period, I reinstalled the system, updated the graphics card driver, and cleared the Bitwig registry, but none of them worked.

**Comment by Berikai** [comment]
It most probably indicates that the Bitwig installation you try to apply theming is different than the version you try to run. So, I assume you have two or more Bitwig Studio installations on your system.

Check how you start your Bitwig Studio and track the way to its location path. Make sure that you apply theming into the correct jar file.

If it doesn't seem working, try to provide more information for further help ❤️

**Comment by Vocllum** [comment]
Still unresolved.
My original installation path was C:\Program Files\Bitwig Studio\, so there must only be one Bitwig
Then I deleted it and changed it to C:\Program Files\Bitwig Studio\5.2.5\, but it still hasn't been resolved

**Comment by Berikai** [comment]
If the jar file is changing successfully, there shouldn't be any problem. You seem to be doing it as you should be but at the same time after a clean installation you are experiencing the same behaviour, that makes me think that you are maybe missing a step. I couldn't come up with any solution as of right now. You can try the things listed below. I expect one of them will be the solution to the problem.

- Make sure that Bitwig is not running while applying the theme.
- Go to the Bitwig path, try to apply the theme to the jar file there and check if the file's last modified date is changed. Then, start the Bitwig's exe file there to make sure that you are really running the correct program.
- Make sure that the theme file you try to apply is valid. Maybe you try to apply the original theme file you exported. You can load your theme file to https://bitwig.berikai.dev to see if the theme file is valid.
- Try to apply different themes. There is a list of some in https://github.com/berikai/awesome-bitwig-themes
- Try running the theme editor as admin. You can also try to run via command line if you used GUI previously or vice versa. Using commandline may actually be helpful since it also shows detailed error logs if any error happens.
- In case of any filesystem permission issues, copy bitwig.jar to another file and apply the theme to that jar file there. Then you can replace bitwig.jar file with the modified one.

Let me know if any of these steps help!

**Comment by Vocllum** [comment]
Thank you very much for your help! The problem has been resolved!
The files in the C drive require administrator privileges to modify, but I failed to launch the theme editor with administrator privileges. I copied the jar to another location, modified it, and replaced it successfully! But I still don't know why the exported theme is already replaced.
Anyway, thank you for your help!

**Comment by Berikai** [comment]
Super happy to hear that! Have a good one ❤️
